# Generated by Django 5.0.6 on 2024-05-08 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_insurance', '0002_agentavailability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentavailability',
            name='lattitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='agentavailability',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
