# Generated by Django 5.0.6 on 2024-06-14 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_insurance', '0002_feedback_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='Contact_Info',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='policy',
            name='PolicyType',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='policy',
            name='Policy_Number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='policy',
            name='RenewalDate',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='policy',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
