# Generated by Django 5.0.4 on 2024-05-09 17:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("online_insurance", "0003_agentavailability_agent"),
        ("online_insurance", "0004_agentavailability_agent_district"),
    ]

    operations = []
