# Generated by Django 5.0.4 on 2024-05-19 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_insurance', '0006_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='agentavailability',
            name='agent',
            field=models.CharField(max_length=100),
        ),
    ]
