# Generated by Django 5.0.4 on 2024-05-30 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("online_insurance", "0009_feedback"),
        ("online_insurance", "0009_userprofile"),
    ]

    operations = []
